# Generated by Django 4.2.1 on 2023-05-25 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(default=0)),
                ('notaNegociacao', models.IntegerField(default=5)),
                ('notaClickAutos', models.IntegerField(default=5)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('aprovada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField(blank=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_usuario', to=settings.AUTH_USER_MODEL)),
                ('usuario_avaliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_usuario_avaliado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Avaliações',
                'ordering': ('usuario_avaliado',),
            },
        ),
    ]
